# Generated by Django 4.2.6 on 2023-11-03 17:39

from django.db import migrations, models
import secondmini.models


class Migration(migrations.Migration):

    dependencies = [
        ('secondmini', '0004_alter_departments_dep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(max_length=254, validators=[secondmini.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_name',
            field=models.CharField(max_length=255, validators=[secondmini.models.validate]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_phone',
            field=models.CharField(max_length=10, validators=[secondmini.models.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(max_length=255, validators=[secondmini.models.validate]),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_spec',
            field=models.CharField(max_length=255, validators=[secondmini.models.validate]),
        ),
    ]
